### ISSUE TITLE
I can´t generate a field anymore TypeError

### ISSUE THREAD

**Issue by oceanmattes** [FieldRobotEvent/Virtual_Field_Robot_Event_21#64]
i cloned the git repository "virtual_maize_field" with the latest changes, but i can´t generate a field anymore:
rosrun virtual_maize_field generate_world.py
Traceback (most recent call last):
  File "/home/matthias/catkin_ws/src/virtual_maize_field/src/virtual_maize_field/generate_world.py", line 188, in <module>
    main()
  File "/home/matthias/catkin_ws/src/virtual_maize_field/src/virtual_maize_field/generate_world.py", line 173, in main
    generator = WorldGenerator(args)
  File "/home/matthias/catkin_ws/src/virtual_maize_field/src/virtual_maize_field/generate_world.py", line 22, in init
    self.wd = WorldDescription(kwargs)
TypeError: init() got an unexpected keyword argument 'show_map'

**Comment by Rick-v-E** [comment]
Hi, I moved your issue to the `virtual_maize_field` repository.
